config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/users/:id', to: 'user#show'
  patch'/users/:id', to: 'user#update'
  resources :posts
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  def user
    return User.find_by(id: self.user_id)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :posts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller? 
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    posts_path 
  end

  def after_sign_out_path_for(resource)
    new_user_session_path 
  end



  private
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:name]) 
    end
    
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @event = Event.all
  end

  def new
    @event = Event.new
  end


  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    if @event.save
      redirect_to events_path
    else
      render 'new'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

  def show
  end


private
  def event_params
    params.require(:event).permit(:user_id, :event_name)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end


  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def show
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

private
  def post_params
    params.require(:post).permit(:user_id, :context, :image)
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController


  def show
    @user = User.find_by(id: params[:id])
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:birthday, :mood, :brand, :taste, :food_genre, :is_public, :name, :password, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/events/index.html.erb
<h1>イベント一覧</h1>

<td><%= link_to '新規作成', new_event_path %></td>

<table>

  <tbody>
    <% @event.each do |event| %>
    <tr>
    <td><%= event.event_name %></td>
    <td><%= post.user.name %></td>
    <td><%= image_tag post.image if post.image.attached? %></td>
    <td><%= link_to '削除', post, method: :delete, data: { confirm: 'You sure?' }, class: "btn btn-danger" %></td>
    </tr>
    <% end %>



  </tbody>
</table>

app/views/events/new.html.erb
<h1>新規作成</h1>

<%= form_with model: @event do |f| %>
<div class="field">
  <%= f.label :イベント %><br>
  <%= f.text_field :event_name %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/post/index.html.erb
<h1>投稿一覧</h1>

<%= link_to '新規作成', new_post_path %>

<table>
  <thead>
    <tr>
      <th>投稿</th>
      <th>本文</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.body %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/post/new.html.erb
<h1>新規作成</h1>

<%= link_to '一覧へ', post_index_url %>

<%= form_with model: @post do |f| %>
<div class="field">
  <%= f.label :投稿内容 %><br>
  <%= f.text_field :title %>
</div>
<div class="field">
  <%= f.label :詳細 %><br>
  <%= f.text_field :body %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>

<td><%= link_to '新規作成', new_post_path %></td>
<%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>

<table>

  <tbody>
    <% @posts.each do |post| %>
    <tr>
    <td><%= post.context %></td>
    <td><%= post.user.name %></td>
    <td><%= image_tag post.image if post.image.attached? %></td>
    <td><%= link_to '削除', post, method: :delete, data: { confirm: 'You sure?' }, class: "btn btn-danger" %></td>
    </tr>
    <% end %>



  </tbody>
</table>

app/views/posts/new.html.erb
<h1>新規作成</h1>

<%= link_to '一覧へ', posts_path %>
<%= form_with model: @post do |f| %>
<div class="field">
  <%= f.label :詳細 %><br>
  <%= f.text_field :context %>
   <%= f.label :画像 %><br />
   <%= f.file_field :image, class: "image" %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/users/edit.html.erb
<%=form_with model: @user do |form| %>
<%= form.label :name, "なまえ" %>
<%= form.text_field :name %>

<%= form.label :birthday, "たんじょうび" %>
<%= form.date_field :birthday %>

<%= form.label :mood, "ふんいき" %>
<%= form.range_field :mood, in: 1..100 %>

<%= form.label :brand, "ブランド" %>
<%= form.text_field :brand %>

<%= form.label :taste, "食の好み" %>
<%= form.text_field :taste %>



<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>さんのプロフィール</h1>